import type { Metadata } from "next";
import "./globals.css";
import "@/components/AdminSidebar";
import AdminSidebar from "@/components/AdminSidebar";
import AdminTopbar from "@/components/AdminTopbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased flex min-h-screen"
      >
        <AdminSidebar/>
        <main className="bg-sunlight-soft w-full">
          <AdminTopbar/>
          {children}
        </main>
      </body>
    </html>
  );
}
